//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLMaker2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public short ZoneMax {
            get {
                return ((short)(this["ZoneMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"東京:tokyo
大阪:osaka
愛知:aichi
北海道:hokkaido
宮城:miyagi
広島:hiroshima
福岡:fukuoka
青森:aomori
岩手:iwate
秋田:akita
山形:yamagata
福島:fukushima
茨城:ibaragi
栃木:tochigi
群馬:gunma
山梨:yamanashi
新潟:niigata
長野:nagano
神奈川:kanagawa
埼玉:saitama
千葉:chiba
岐阜:gifu
三重:mie
静岡:shizuoka
兵庫:hyogo
京都:kyoto
奈良:nara
滋賀:shiga
和歌山:wakayama
富山:toyama
石川:ishikawa
福井:fukui
鳥取:tottori
徳島:tokushima
香川:kagawa
愛媛:ehime
高知:kochi
島根:shimane
岡山:okayama
山口:yamaguchi
佐賀:saga
長崎:nagasaki
熊本:kumamoto
大分:oita
宮崎:miyazaki
鹿児島:kagoshima
沖縄:okinawa")]
        public string ApList {
            get {
                return ((string)(this["ApList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC-sphere")]
        public string CName {
            get {
                return ((string)(this["CName"]));
            }
        }
    }
}
